DataFile C:\GitHub\eeglab\functions\sigprocfunc\binica.fdt
chans 128
frames 30720
WeightsOutFile C:\GitHub\eeglab\functions\sigprocfunc\binica.wts
SphereFile C:\GitHub\eeglab\functions\sigprocfunc\binica.sph
sphering on
bias on
extended 1
pca 127
lrate 0.001
blocksize 0
stop 1.0e-7
maxsteps 512
posact off
annealstep 0.98
annealdeg 60
momentum 0
verbose off